In [ ]:
#Matrix operation
!pip install numpy

In [2]:
import numpy as np

In [3]:
n = np.array((1,2,3,4))
print(n)

[1 2 3 4]


In [4]:
print(type(n))

<class 'numpy.ndarray'>


In [6]:
A = np.array([
    [1,2,3],
     [4,5,6],
     [7,8,9]
])

print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

B = np.array([
    [9,8,7],
    [6,5,4],
    [3,2,1]
])

print(A+B)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [18]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

B = np.array([
    [9,8,7],
    [6,5,4],
    [3,2,1]
])

print(A-B)

[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


In [13]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

B = np.array([
    [9,8,7],
    [6,5,4],
    [3,2,1]
])

print(B-A)

[[ 8  6  4]
 [ 2  0 -2]
 [-4 -6 -8]]


In [22]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

B = np.array([
    [9,8,7],
    [6,5,4],
    [3,2,1]
])

print( A * B)

[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [23]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

B = np.array([
    [9,8,7],
    [6,5,4],
    [3,2,1]
])
print(A .dot(B)   )

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [25]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

B = np.array([
    [9,8,7],
    [6,5,4],
    [3,2,1]
])
print( np.dot(A,B)  )

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [27]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

B = np.array([
    [9,8,7],
    [6,5,4],
    [3,2,1]
])

print( np.matmul(A,B))

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [29]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

B = np.array([
    [9,8,7],
    [6,5,4],
    [3,2,1]
])

print(A@B)

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [30]:
A = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print(    np.linalg.inv(A)    )

[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


In [33]:
A = np.array([[2, 4], [1, 2]])
print(      np.linalg.eigvals(A))

[4. 0.]


In [44]:
x = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

y = np.array([
    [9,8,7],
    [6,5,4],
    [3,2,1]
])

result = [
    [0,0,0],
    [0,0,0],
    [0,0,0]
]

for i in range(len(x)):
    for j in range(len(y[0])):
        for k in range(len(y)):
            result[i][j] += x[i][k] * y[k][j]

for r in result:
    print(r)

[30, 24, 18]
[84, 69, 54]
[138, 114, 90]


In [37]:
A = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

B = [
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
]

result = [
    [0, 0, 0],
    [0, 0, 0],
    [0, 0, 0]
]

for i in range(len(A)):  
    for j in range(len(B[0])): 
        for k in range(len(A[0])):  
            result[i][j] += A[i][k] * B[k][j]
for row in result:
    print(row)

[30, 24, 18]
[84, 69, 54]
[138, 114, 90]


In [46]:
A = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

B = [
    [9,8,7],
    [6,5,4],
    [3,2,1]
]

result = [
    [0,0,0],
    [0,0,0],
    [0,0,0]
]

for i in range(len(A)):
    for j in range(len(B[0])):
        for k in range(len(B[0])):
            result[i][j] += A[i][k] * B[k][j]

for s in result:
    print(s)
            

[30, 24, 18]
[84, 69, 54]
[138, 114, 90]
